# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '16.0'
target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
    pod 'Adjust', '5.0.0'
end